apiVersion: v1
kind: Service
metadata:
  name: movieapp
  labels:
    app: movieapp
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: movieapp
  type: LoadBalancer
